name: CI # The name of the workflow
on:
  push:
    branches: [ "mini-internet" ] # Triggers the workflow on push events to the main branch

jobs:
  build: # The name of the job
    runs-on: ubuntu-latest # The type of machine (runner) to run the job on

    steps:
    - uses: actions/checkout@v4 # Checks out your repository code

    - name: Install dependencies
      run: npm install # Runs a command using the runner's shell

    - name: Run tests
      run: npm test # Runs the test command
